name: Deploy

on:
  push:
    tags: v*
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      
    - name: Run release build
      run: shards build --release
    - name: Pack release file
      run: |
        cp ./bin/charqui .
        tar -zcvf charqui-${{ matrix.os }}-${{ github.ref_name}}.tar.gz charqui
    - name: "Automatic Release"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}
        path: charqui-${{ matrix.os }}-${{ github.ref_name}}.tar.gz
